### ISSUE TITLE
regexp for audio

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#10]
something I found missing from awesomeTTS is regexp rules for audio. Can we add them back?

**Comment by lucwastiaux** [comment]
can you tell me your use cases ?

**Comment by mrderiuzz** [comment]
I am using some shortened version of words so that they don't take space unnecessarily but when hearing to audio I'd like to hear full version. Consider this example:

`unter (etw +D)`
![image](https://user-images.githubusercontent.com/24499888/107741535-a7abf900-6d0d-11eb-9b5b-8ade720f6977.png)

expected audio would be: etwas +Dativ

In German there are lots of them: jdm -> jemandem, etw -> etwaas, jdn -> jemanden, usw.

I had these rules implemented through regexp in awesomeTTS, it would be nice to have it in language tools too

**Comment by lucwastiaux** [comment]
OK. This functionality is definitely coming.

**Comment by lucwastiaux** [comment]
should be available now. Please try it out and report any issues.

**Comment by lucwastiaux** [comment]
If you're happy with the current functionality, i'll close this.
