### ISSUE TITLE
crash when changing deck name for which audio generation rules are set

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#12]
as in the title, I have a deck X for which I configured auto-generation of audio files. Then I change its name to Y and obviously these rules ceased to exist (perhaps they should)? Well anyways I wanted to reconfigure them and my anki is now crashing when I open the audio generation view:

![image](https://user-images.githubusercontent.com/24499888/106157308-dd37da80-6182-11eb-856b-f888c6546fb2.png)

**Comment by lucwastiaux** [comment]
Thanks, let me try to take a look and fix this bug. Is it blocking you ? If yes, you can try to reset your config for Language Tools to the default config. But you will have to re-do language mapping, etc.

**Comment by mrderiuzz** [comment]
I actually managed to troubleshoot this in the meantime. This happens when language is not mapped for a given deck. I opened language mapping, did the automatic detection again and everything is back to normal :) 

so probably there should be some kind of warning that there's no mapping for this deck

**Comment by lucwastiaux** [comment]
I think this crash in particular happened before you didn't have any notes selected when you clicked the menu item.

**Comment by mrderiuzz** [comment]
oh that could be it. I also didn't have the languages mapped for this deck but happy to test it out in the update
