### ISSUE TITLE
Language Tools is causing Anki to freeze

### ISSUE THREAD

**Issue by brothamanben** [lucwastiaux/anki-language-tools#13]
When I go click _language _mapping__ it causes Anki to freeze 

![image](https://user-images.githubusercontent.com/68020961/106228149-bb436400-6225-11eb-9c66-9db3754be43d.png)

**Comment by lucwastiaux** [comment]
Hi, I'm investigating some performance issues that other users have reported as well. Could you send me your deck ?
From the Anki main screen, click File → Export, click Export... . Then locate apkg file you just created, and upload it to https://www.dropbox.com/request/X9L4mhPqEcfvKFuSm2nK

**Comment by brothamanben** [comment]
> Hi, I'm investigating some performance issues that other users have reported as well. Could you send me your deck ?
> From the Anki main screen, click File → Export, click Export... . Then locate apkg file you just created, and upload it to https://www.dropbox.com/request/X9L4mhPqEcfvKFuSm2nK

Okay will do, thanks

**Comment by mrderiuzz** [comment]
@brothamanben already reported in #3, I presume this is the same thing (as long as it actually does open for you after 1m or so)

**Comment by lucwastiaux** [comment]
I just released Language Tools 1.4 which should fix this.
