### ISSUE TITLE
crashing when closing the edit modal before the audio generates

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#14]
as in the title, when I'm in review mode, then click 'e' to edit the card, change a field (that is supposed to auto generate audio) and then click escape quickly, then I get an error. This is somewhat expected because the audio will not generate that fast but it just simply should not be an error (or maybe a warning instead, like "You want to exit editing mode without updating audio, are you  sure?")

![image](https://user-images.githubusercontent.com/24499888/106244652-888c7200-620b-11eb-8739-dd3aae7321a8.png)

**Comment by lucwastiaux** [comment]
Thanks for reporting this. I'll look into such a warning message. Alternatively, would it help if there was an indicator that the audio is loading ?

**Comment by mrderiuzz** [comment]
yeah, loading indicator sounds good

**Comment by lucwastiaux** [comment]
The crash should be fixed in v1.6, just released, thanks for reporting. Loading indicator is not yet done, let me create a separate issue.
