### ISSUE TITLE
audio is not auto-generating when there's ":" in the text

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#15]
see example:
![image](https://user-images.githubusercontent.com/24499888/106351247-6d893300-62db-11eb-9e1a-19bac4530c7b.png)

it won't auto-generate the audio for me. But when I remove it, or change to "," then it works. I assume it's a bug?

**Comment by lucwastiaux** [comment]
can you copy the full text for me please ?

**Comment by mrderiuzz** [comment]
`anders: es hängt von jemandem oder etwas ab`

**Comment by lucwastiaux** [comment]
Awesome thanks, I see the issue, I should have a fix soon !
