### ISSUE TITLE
randomly adding audio to empty fields

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#17]
I encountered an issue where language tools generate audio, according to 'auto-generate' rules, when the field is empty (?). 

I tried to reproduce it on the GIF below, please check it out. It might be happening when switching to other note type, deck, or field:

![2021-02-06_14h23_03](https://user-images.githubusercontent.com/24499888/107119342-38ef1b80-6887-11eb-9fc6-a2872ce3831e.gif)

This does not affect anything but has somewhat messed up with my media files, as Anki reports there are missing audio files that are non-existent:

![image](https://user-images.githubusercontent.com/24499888/107119355-4d331880-6887-11eb-9065-dd72fd3e04c5.png)

please look into this. Let me know if you need some further information from my side :)

**Comment by lucwastiaux** [comment]
Thanks for reporting this. Empty fields should be handled better yes. It makes no sense at all to generate empty sound files.

After adding a new note and waiting sufficient time for the audio to generate, do you find that the audio is ever missing from your collection at this point ? In other words, is the audio always missing from your collection when it's automatically generated from the "new note" dialog ?

**Comment by mrderiuzz** [comment]
Not sure if I understood you correctly but if I you mean: is the audio ever missing when it should be generated, fhen yes and no. Sometimes updating the field does not trigger automatic regeneration. I'm that case I cut field's content, wait 1.5s and paste it back in. But it's hard for me to reproduce consistently but if I will be able to do so, I'll open a separate issue for that :)

**Comment by lucwastiaux** [comment]
The UI should definitely do a better job of telling you what sound got generated. Let me think about it a little bit. And thank you so much again for reporting issues, it's super valuable.

**Comment by lucwastiaux** [comment]
Empty fields generating audio should be gone now, I just released 1.6 which fixes this, as well as a few other crashes.
