### ISSUE TITLE
no error message when API key expires

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#21]
today when editing note i spotted a weird behaviour, collapsing audio fields:

![image](https://user-images.githubusercontent.com/24499888/107742035-9a433e80-6d0e-11eb-8e6c-0c2b8a566292.png)

I was confused for a second but then checked API through -> verify API key and it said it expired. It'd be nice to have some kind of warning when API key is expired and that is why audio is not being generated

**Comment by lucwastiaux** [comment]
Were you using the collective API key up until now?

**Comment by lucwastiaux** [comment]
I'm adding some better error checking in this area very soon.

**Comment by mrderiuzz** [comment]
oh I might have been, I never generated a patreon API key before. So if it automatically prolongs then I guess we can close this
