### ISSUE TITLE
Language Mapping view should have collapsable rows, and decks groupped by parent deck 

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#23]
In Language Mapping view decks names are sorted alphabetically, regardless of their parent deck, which makes it hard to find subdecks. Expected behaviour would be to be groupped together by parent deck.

Also, with a lot of (sub)decks and notes types it is very hard to find a particular deck. Would be nice to get a button "collapse all" and then un-collapse certain deck and its subdecks

**Comment by lucwastiaux** [comment]
Or some kind of filtering logic

**Comment by lucwastiaux** [comment]
For now, I've added filtering based on a text field. This can cover nested decks because their name contains the parent deck's name. So this should allow easy access to the wanted deck. Please give it a try and let me know whether this is sufficient.

**Comment by mrderiuzz** [comment]
yeah it does the trick, thanks!
