### ISSUE TITLE
tripple "Speak" or "Play" buttons

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#24]
Is it normal that I get these buttons thrice?

![image](https://user-images.githubusercontent.com/24499888/109309980-42dfbb00-7844-11eb-8fce-d89a00efe184.png)

Here's the mapping for the deck that this card is in:

![image](https://user-images.githubusercontent.com/24499888/109310086-63a81080-7844-11eb-9be4-91c170e7c188.png)

**Comment by lucwastiaux** [comment]
NOT normal, thanks for reporting! Do I already have a copy of your deck?

**Comment by mrderiuzz** [comment]
Unfortunately, in the meantime I've changed the language mapping for this deck and the problem fixed itself. I'd need to restore (one of, not sure which) anki addons github's previous commits to fetch this which would be hard, so closing
