### ISSUE TITLE
error message when audio cannot be generated

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#25]
when pasting "enriched" (containing invisible spaces or other HTML markup) text into Anki without cleaning it first, it will fail to generate audio. Currently, there's no warning about it, audio file simply appears in the field as always but it'll be silent. If you have autoplay disabled or listening to music or whatever you will not spot this.

Example: Geschwindigkeit des Wachstums (it will probably paste itself on github in a clean state, but i copied it from here: https://de.thefreedictionary.com/Wachstumstempo)

Can we get some kind of warning, maybe a popup or maybe a red dot next to "Speak" button that would indicate that the string is broken and there'll be no sound?

![image](https://user-images.githubusercontent.com/24499888/109312424-55a7bf00-7847-11eb-80e9-d544288a9bd8.png)

**Comment by lucwastiaux** [comment]
I believe this should be fixed now, no audio will be generated if the field is blank after stripping html
