### ISSUE TITLE
Language Mapping view long loading time

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#3]
as in the title. I have a lot of decks / note types and it literally freezes anki for me for like 1m or so:

![image](https://user-images.githubusercontent.com/24499888/106040765-2f252580-60db-11eb-90db-893b4cb7c9a0.png)

is there anything we could do about it? I see there's a lot of fields but maybe we could open them in a collapsed view or something

**Comment by lucwastiaux** [comment]
How many decks and note types do you have in total ?

**Comment by mrderiuzz** [comment]
i don't know how to easily count this but far too many to count manually :) but I sent you my entire collection on a dropbox sometime ago, would it be possible to check there?

**Comment by lucwastiaux** [comment]
I think I have a fix for this. it'll be in the next release.

**Comment by lucwastiaux** [comment]
I just released Language Tools 1.4 which fixes this.
