### ISSUE TITLE
when trying to add audio to unmapped deck, there should be a warning

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#30]
as in the title, when a deck is not mapped and I try adding audio to it, I got an error "out of index", as shown on the GIF below. Expecting a message informing me to finish mapping first instead.

(btw yes, deck languages mapping is real-time on the GIF and it does take that much to load)

![2021-03-21_21h25_50](https://user-images.githubusercontent.com/24499888/111919863-4bff2900-8a8c-11eb-922e-0871304f48a2.gif)

**Comment by lucwastiaux** [comment]
done in 2.4, please check. also added some automated tests.

opening a new tick for language mapping performance issues
