### ISSUE TITLE
audio voice selection opens too big when there are pictures

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#4]
for some options there are pics loaded and there's no control on their size. Can we maybe put some kind of max-width on them? I can't even scroll down to this window to make it smaller

![image](https://user-images.githubusercontent.com/24499888/106041045-97740700-60db-11eb-9186-0adc7f398f17.png)

**Comment by lucwastiaux** [comment]
should be sorted with HTML stripping on the sample text.
