### ISSUE TITLE
crash when adding audio through preprocessing

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#43]
as in the title. Check the following recording:

https://user-images.githubusercontent.com/24499888/123606614-5bb1aa80-d7fd-11eb-884b-df9e650aa50f.mp4

for example: the rule "\(jdm\)" should transform to "jemandem" and yet it crashes with "no field empty" method error

**Comment by lucwastiaux** [comment]
as mentioned, the crash should be fixed in 3.4, and i'm working on simple, non regexp replacements.
