### ISSUE TITLE
Voice Selection: freezing when switching to other lanagues

### ISSUE THREAD

**Issue by mrderiuzz** [lucwastiaux/anki-language-tools#6]
![image](https://user-images.githubusercontent.com/24499888/106041525-313bb400-60dc-11eb-9d03-95046ae1b9d3.png)
it takes a good moment when switching languages in Audio Selection view. If you click anything on that window when it's loading it's gonna break, like become all white and stuff. 

can we get some kind of loading animation here, or anything? also blocking the window from being clicked on would help

**Comment by lucwastiaux** [comment]
Are your images in separate fields ? They should obviously be ignored by language tools. If you map those fields to "unset" in the language mapping, then those images shouldn't show up when you select "Czech" language.

**Comment by mrderiuzz** [comment]
Images are in separate fields - can we double-check if in a field there's
only image it would map to not set?

**Comment by lucwastiaux** [comment]
So the interesting thing that happened is that one of your "image" fields was detected as Czech language. If I mark the language manually to "Not set" for that field, the images stop appearing. That dialog was never intended to show images, I guess the automatic HTML processing in the labels is doing that.
I think I can try to ignore those fields in the detection.

How long do you experience the freeze for ? I just checked with your german deck, and the freeze when switching languages is just 
1 second.

Do yourself a favor and mark those image fields as "Not set" for now, it'll make everything smoother

**Comment by mrderiuzz** [comment]
yeah I will remap my decks but just waiting for some resolution to #3, hopefully collapsing the decks as I only need to map languages in my language decks, which is just 2 (no need to do for others)

**Comment by lucwastiaux** [comment]
I released a change to language detection which should ignore sound and image fields. It should also not display images in the voic selection screen.

@mrderiuzz how long is the pause when you switch languages ?

**Comment by lucwastiaux** [comment]
I finally experienced this, after importing a french deck with 50k notes. So this requires a large number of notes to manifest itself. It's due to the search for non-empty fields within those notes.  I think I know how to make it faster.

**Comment by lucwastiaux** [comment]
should be fixed in 2.4
