### ISSUE TITLE
Can't generate random samples

### ISSUE THREAD

**Issue by boonethetoon** [lucwastiaux/anki-language-tools#70]
This may be related to the update because this is the first time I've tried to select a voice.  I've reinstalled and of course restarted Anki. 

![image](https://user-images.githubusercontent.com/91803620/135730859-ce548e63-2f89-422b-8c44-e75b5dc526e8.png)

**Comment by lucwastiaux** [comment]
Do you have any fields mapped to english in the language mapping screen ?

**Comment by boonethetoon** [comment]
Doh! Thank you!
